const productsArray = [
    {
        id: 1,
        name: 'iPhone 11',
        description: 'This is iPhone 11',
        type: 'phone',
        capacity: 64,
        price: 500,
        image: '/images/iPhone-11.jpg',
    },
    {
        id: 2,
        name: 'iPhone 13 mini',
        description: 'This is iPhone 13 mini',
        type: 'phone',
        capacity: 128,
        price: 700,
        image: '/images/iPhone-13-mini.jpg',
    },
    {
        id: 3,
        name: 'iPhone 13 Pro',
        description: 'This is iPhone 13 Pro',
        type: 'phone',
        capacity: 65,
        price: 500,
        image: '/images/iPhone-13Pro.jpg',
    },
    {
        id: 4,
        name: 'iPhone 13',
        description: 'This is iPhone 13',
        type: 'phone',
        capacity: 512,
        price: 800,
        image: '/images/iPhone-13.jpg',
    },
    {
        id: 5,
        name: 'iPhone 12',
        description: 'This is iPhone 12',
        type: 'phone',
        capacity: 65,
        price: 550,
        image: '/images/iPhone-12.jpg',
    },
    {
        id: 6,
        name: 'iPhone 12 Pro Max',
        description: 'This is iPhone 12 Pro Max',
        type: 'phone',
        capacity: 1024,
        price: 1200,
        image: '/images/iPhone-12-Pro-Max.jpg',
    },
]

export default productsArray
